// Auto-generated from MetroFlow_Dataset/metro_stations.csv — real Indian metro stations.
import type { CrowdLevel } from "@/lib/utils";

export type Station = {
  id: string; name: string; code: string; metro: string; city: string;
  line: string; category: string; interchange: boolean; footfall: number;
  level: CrowdLevel; occupancy: number;
};

export const STATIONS: Station[] = [
  {
    "id": "DEL018",
    "name": "Central Secretariat",
    "code": "DEL-CEN",
    "metro": "Delhi Metro",
    "city": "Delhi",
    "line": "Yellow Line / Violet Line",
    "category": "Railway Connection",
    "interchange": true,
    "footfall": 306017,
    "level": "High",
    "occupancy": 80
  },
  {
    "id": "DEL015",
    "name": "New Delhi",
    "code": "DEL-NEW",
    "metro": "Delhi Metro",
    "city": "Delhi",
    "line": "Yellow Line / Airport Express",
    "category": "Railway Connection",
    "interchange": true,
    "footfall": 303868,
    "level": "High",
    "occupancy": 74
  },
  {
    "id": "DEL072",
    "name": "Mayur Vihar Phase-1",
    "code": "DEL-MAY",
    "metro": "Delhi Metro",
    "city": "Delhi",
    "line": "Blue Line / Pink Line",
    "category": "Commercial",
    "interchange": true,
    "footfall": 274696,
    "level": "Critical",
    "occupancy": 93
  },
  {
    "id": "DEL038",
    "name": "Dwarka Sector 21",
    "code": "DEL-DWA",
    "metro": "Delhi Metro",
    "city": "Delhi",
    "line": "Blue Line / Airport Express",
    "category": "Commercial",
    "interchange": true,
    "footfall": 273044,
    "level": "High",
    "occupancy": 78
  },
  {
    "id": "DEL006",
    "name": "Azadpur",
    "code": "DEL-AZA",
    "metro": "Delhi Metro",
    "city": "Delhi",
    "line": "Yellow Line / Pink Line",
    "category": "Commercial",
    "interchange": true,
    "footfall": 272277,
    "level": "Critical",
    "occupancy": 90
  },
  {
    "id": "DEL188",
    "name": "Anand Vihar ISBT",
    "code": "DEL-ANA",
    "metro": "Delhi Metro",
    "city": "Delhi",
    "line": "Pink Line",
    "category": "Railway Connection",
    "interchange": true,
    "footfall": 269077,
    "level": "High",
    "occupancy": 82
  },
  {
    "id": "MUM008",
    "name": "Marol Naka",
    "code": "MUM-MAR",
    "metro": "Mumbai Metro",
    "city": "Mumbai",
    "line": "Line 1 (Blue) / Line 3 (Aqua)",
    "category": "IT Hub",
    "interchange": true,
    "footfall": 234015,
    "level": "High",
    "occupancy": 75
  },
  {
    "id": "MUM004",
    "name": "Andheri",
    "code": "MUM-AND",
    "metro": "Mumbai Metro",
    "city": "Mumbai",
    "line": "Line 1 (Blue)",
    "category": "IT Hub",
    "interchange": true,
    "footfall": 215484,
    "level": "Critical",
    "occupancy": 99
  },
  {
    "id": "MUM002",
    "name": "D.N. Nagar",
    "code": "MUM-DNN",
    "metro": "Mumbai Metro",
    "city": "Mumbai",
    "line": "Line 1 (Blue) / Line 2A (Yellow)",
    "category": "Commercial",
    "interchange": true,
    "footfall": 200694,
    "level": "Critical",
    "occupancy": 98
  },
  {
    "id": "CHN016",
    "name": "Chennai Central Metro",
    "code": "CHN-CH2",
    "metro": "Chennai Metro",
    "city": "Chennai",
    "line": "Blue Line / Green Line",
    "category": "Railway Connection",
    "interchange": true,
    "footfall": 189239,
    "level": "High",
    "occupancy": 81
  },
  {
    "id": "HYD011",
    "name": "Ameerpet",
    "code": "HYD-AME",
    "metro": "Hyderabad Metro",
    "city": "Hyderabad",
    "line": "Red Line / Blue Line",
    "category": "Commercial",
    "interchange": true,
    "footfall": 188720,
    "level": "Critical",
    "occupancy": 90
  },
  {
    "id": "BLR015",
    "name": "Majestic",
    "code": "BLR-MAJ",
    "metro": "Bengaluru Metro",
    "city": "Bengaluru",
    "line": "Purple Line / Green Line",
    "category": "Railway Connection",
    "interchange": true,
    "footfall": 162748,
    "level": "High",
    "occupancy": 74
  },
  {
    "id": "CHN005",
    "name": "St. Thomas Mount",
    "code": "CHN-STT",
    "metro": "Chennai Metro",
    "city": "Chennai",
    "line": "Blue Line / Green Line",
    "category": "Commercial",
    "interchange": true,
    "footfall": 131803,
    "level": "High",
    "occupancy": 86
  },
  {
    "id": "BLR019",
    "name": "MG Road",
    "code": "BLR-MGR",
    "metro": "Bengaluru Metro",
    "city": "Bengaluru",
    "line": "Purple Line",
    "category": "Commercial",
    "interchange": true,
    "footfall": 127332,
    "level": "High",
    "occupancy": 78
  },
  {
    "id": "KOL010",
    "name": "Central",
    "code": "KOL-CEN",
    "metro": "Kolkata Metro",
    "city": "Kolkata",
    "line": "Blue Line",
    "category": "Railway Connection",
    "interchange": false,
    "footfall": 126341,
    "level": "High",
    "occupancy": 77
  },
  {
    "id": "KOL034",
    "name": "Sealdah",
    "code": "KOL-SEA",
    "metro": "Kolkata Metro",
    "city": "Kolkata",
    "line": "Green Line",
    "category": "Railway Connection",
    "interchange": true,
    "footfall": 120248,
    "level": "High",
    "occupancy": 86
  },
  {
    "id": "BLR032",
    "name": "Nallurhalli",
    "code": "BLR-NAL",
    "metro": "Bengaluru Metro",
    "city": "Bengaluru",
    "line": "Purple Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 120083,
    "level": "Critical",
    "occupancy": 95
  },
  {
    "id": "CHN004",
    "name": "Arignar Anna Alandur",
    "code": "CHN-ARI",
    "metro": "Chennai Metro",
    "city": "Chennai",
    "line": "Blue Line / Green Line",
    "category": "Commercial",
    "interchange": true,
    "footfall": 119056,
    "level": "High",
    "occupancy": 82
  },
  {
    "id": "BLR021",
    "name": "Halasuru",
    "code": "BLR-HAL",
    "metro": "Bengaluru Metro",
    "city": "Bengaluru",
    "line": "Purple Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 116990,
    "level": "Critical",
    "occupancy": 93
  },
  {
    "id": "BLR029",
    "name": "Hoodi",
    "code": "BLR-HOO",
    "metro": "Bengaluru Metro",
    "city": "Bengaluru",
    "line": "Purple Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 115891,
    "level": "High",
    "occupancy": 86
  },
  {
    "id": "HYD041",
    "name": "Parade Ground",
    "code": "HYD-PA2",
    "metro": "Hyderabad Metro",
    "city": "Hyderabad",
    "line": "Blue Line",
    "category": "Residential",
    "interchange": true,
    "footfall": 115647,
    "level": "Critical",
    "occupancy": 99
  },
  {
    "id": "HYD020",
    "name": "MG Bus Station",
    "code": "HYD-MGB",
    "metro": "Hyderabad Metro",
    "city": "Hyderabad",
    "line": "Red Line / Green Line",
    "category": "Railway Connection",
    "interchange": true,
    "footfall": 113812,
    "level": "Critical",
    "occupancy": 93
  },
  {
    "id": "HYD031",
    "name": "Madhapur",
    "code": "HYD-MAD",
    "metro": "Hyderabad Metro",
    "city": "Hyderabad",
    "line": "Blue Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 111977,
    "level": "High",
    "occupancy": 74
  },
  {
    "id": "KOL012",
    "name": "Esplanade",
    "code": "KOL-ESP",
    "metro": "Kolkata Metro",
    "city": "Kolkata",
    "line": "Blue Line / Green Line",
    "category": "Residential",
    "interchange": true,
    "footfall": 111182,
    "level": "High",
    "occupancy": 85
  },
  {
    "id": "MUM006",
    "name": "Chakala (J.B. Nagar)",
    "code": "MUM-CHA",
    "metro": "Mumbai Metro",
    "city": "Mumbai",
    "line": "Line 1 (Blue)",
    "category": "Commercial",
    "interchange": false,
    "footfall": 110476,
    "level": "High",
    "occupancy": 86
  },
  {
    "id": "MUM009",
    "name": "Saki Naka",
    "code": "MUM-SAK",
    "metro": "Mumbai Metro",
    "city": "Mumbai",
    "line": "Line 1 (Blue)",
    "category": "Commercial",
    "interchange": false,
    "footfall": 109355,
    "level": "Critical",
    "occupancy": 98
  },
  {
    "id": "KOC015",
    "name": "MG Road",
    "code": "KOC-MGR",
    "metro": "Kochi Metro",
    "city": "Kochi",
    "line": "Line 1 (Blue)",
    "category": "Commercial",
    "interchange": true,
    "footfall": 106541,
    "level": "Critical",
    "occupancy": 94
  },
  {
    "id": "JAI011",
    "name": "Badi Chaupar",
    "code": "JAI-BAD",
    "metro": "Jaipur Metro",
    "city": "Jaipur",
    "line": "Pink Line",
    "category": "Commercial",
    "interchange": true,
    "footfall": 101363,
    "level": "Critical",
    "occupancy": 94
  },
  {
    "id": "AMD003",
    "name": "Rajivnagar",
    "code": "AMD-RAJ",
    "metro": "Ahmedabad Metro",
    "city": "Ahmedabad",
    "line": "Blue Line / Red Line",
    "category": "Residential",
    "interchange": true,
    "footfall": 78439,
    "level": "Medium",
    "occupancy": 55
  },
  {
    "id": "AMD007",
    "name": "Old High Court",
    "code": "AMD-OLD",
    "metro": "Ahmedabad Metro",
    "city": "Ahmedabad",
    "line": "Blue Line / Red Line",
    "category": "IT Hub",
    "interchange": true,
    "footfall": 77044,
    "level": "Medium",
    "occupancy": 66
  },
  {
    "id": "LKO010",
    "name": "Charbagh",
    "code": "LKO-CHA",
    "metro": "Lucknow Metro",
    "city": "Lucknow",
    "line": "Red Line",
    "category": "Railway Connection",
    "interchange": false,
    "footfall": 60420,
    "level": "High",
    "occupancy": 88
  },
  {
    "id": "LKO009",
    "name": "Durgapuri",
    "code": "LKO-DUR",
    "metro": "Lucknow Metro",
    "city": "Lucknow",
    "line": "Red Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 58746,
    "level": "Medium",
    "occupancy": 65
  },
  {
    "id": "KOC020",
    "name": "Vyttila",
    "code": "KOC-VYT",
    "metro": "Kochi Metro",
    "city": "Kochi",
    "line": "Line 1 (Blue)",
    "category": "Commercial",
    "interchange": false,
    "footfall": 58048,
    "level": "Medium",
    "occupancy": 59
  },
  {
    "id": "JAI010",
    "name": "Choti Chaupar",
    "code": "JAI-CHO",
    "metro": "Jaipur Metro",
    "city": "Jaipur",
    "line": "Pink Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 57362,
    "level": "Low",
    "occupancy": 40
  },
  {
    "id": "NDA005",
    "name": "Noida Sector 81",
    "code": "NDA-NO5",
    "metro": "Noida Metro",
    "city": "Noida",
    "line": "Aqua Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 54946,
    "level": "Low",
    "occupancy": 46
  },
  {
    "id": "NGP031",
    "name": "Nagpur Railway Station",
    "code": "NGP-NAG",
    "metro": "Nagpur Metro",
    "city": "Nagpur",
    "line": "Aqua Line",
    "category": "Railway Connection",
    "interchange": false,
    "footfall": 51037,
    "level": "Medium",
    "occupancy": 67
  },
  {
    "id": "NDA003",
    "name": "Noida Sector 76",
    "code": "NDA-NO3",
    "metro": "Noida Metro",
    "city": "Noida",
    "line": "Aqua Line",
    "category": "IT Hub",
    "interchange": false,
    "footfall": 50487,
    "level": "Medium",
    "occupancy": 63
  },
  {
    "id": "NGP030",
    "name": "Cotton Market",
    "code": "NGP-COT",
    "metro": "Nagpur Metro",
    "city": "Nagpur",
    "line": "Aqua Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 43053,
    "level": "Medium",
    "occupancy": 56
  },
  {
    "id": "PUN001",
    "name": "PCMC",
    "code": "PUN-PCM",
    "metro": "Pune Metro",
    "city": "Pune",
    "line": "Purple Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 41485,
    "level": "Medium",
    "occupancy": 61
  },
  {
    "id": "PUN015",
    "name": "Vanaz",
    "code": "PUN-VAN",
    "metro": "Pune Metro",
    "city": "Pune",
    "line": "Aqua Line",
    "category": "IT Hub",
    "interchange": false,
    "footfall": 39713,
    "level": "Medium",
    "occupancy": 57
  },
  {
    "id": "KNP014",
    "name": "Kanpur Central",
    "code": "KNP-KAN",
    "metro": "Kanpur Metro",
    "city": "Kanpur",
    "line": "Orange Line",
    "category": "Railway Connection",
    "interchange": false,
    "footfall": 38673,
    "level": "Medium",
    "occupancy": 68
  },
  {
    "id": "KNP011",
    "name": "Naveen Market",
    "code": "KNP-NAV",
    "metro": "Kanpur Metro",
    "city": "Kanpur",
    "line": "Orange Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 35677,
    "level": "Low",
    "occupancy": 22
  },
  {
    "id": "IDR003",
    "name": "Super Corridor 3",
    "code": "IDR-SU2",
    "metro": "Indore Metro",
    "city": "Indore",
    "line": "Yellow Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 27340,
    "level": "Low",
    "occupancy": 23
  },
  {
    "id": "IDR010",
    "name": "Palasia",
    "code": "IDR-PAL",
    "metro": "Indore Metro",
    "city": "Indore",
    "line": "Yellow Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 25116,
    "level": "Low",
    "occupancy": 30
  },
  {
    "id": "BHO010",
    "name": "Alkapuri",
    "code": "BHO-ALK",
    "metro": "Bhopal Metro",
    "city": "Bhopal",
    "line": "Orange Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 23429,
    "level": "Low",
    "occupancy": 45
  },
  {
    "id": "BHO005",
    "name": "Bharat Talkies",
    "code": "BHO-BHA",
    "metro": "Bhopal Metro",
    "city": "Bhopal",
    "line": "Orange Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 22993,
    "level": "Low",
    "occupancy": 47
  },
  {
    "id": "AGR006",
    "name": "Mankameshwar",
    "code": "AGR-MAN",
    "metro": "Agra Metro",
    "city": "Agra",
    "line": "Yellow Line",
    "category": "IT Hub",
    "interchange": false,
    "footfall": 21158,
    "level": "Low",
    "occupancy": 43
  },
  {
    "id": "AGR011",
    "name": "Jama Masjid",
    "code": "AGR-JAM",
    "metro": "Agra Metro",
    "city": "Agra",
    "line": "Yellow Line",
    "category": "Commercial",
    "interchange": false,
    "footfall": 19653,
    "level": "Low",
    "occupancy": 36
  }
];

export const STATION_COUNT_TOTAL = 725;
export const NETWORK_COUNT = 17;
export const CITY_COUNT = 23;
